name: checkov
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:


jobs:

  scan:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          output_format: cli
          output_file_path: console
        