name: Semgrep Credential Leak Scan

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  semgrep:
    name: Run Semgrep to detect credentials
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      # ✅ 1) Cache pip dependencies SEBELUM install
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # ✅ 2) Install dependencies dari requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt

      # ✅ 3) Run Semgrep (Semgrep sudah di-install via requirements.txt)
      - name: Run Semgrep with rules
        run: |
          semgrep \
            --config p/ci \
            --config p/secrets \
            --config ./semgrep-rules/ \
            --error
