name: Semgrep Credential Scanner

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches: [main, master]
    paths: ['**/.env*', '**/*.php']

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    container: semgrep/semgrep  # PILIHAN 1
    permissions:
      security-events: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Semgrep Scan
        run: |
          semgrep ci \
            --config=p/secrets .semgrep-custom-rules.yml \
            --sarif --output=semgrep-results.sarif \
            --error-on-findings

      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-results.sarif