name: TruffleHog Secret Scan

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --results=verified,unverified,unknown,filtered_unverified

      # - name: TruffleHog OSS
      #   id: trufflehog
      #   uses: trufflesecurity/trufflehog@main
      #   continue-on-error: true
      #   with:
      #     base: ${{ github.event.before }}
      #     head: ${{ github.event.after }}
      #     extra_args: --debug --results=verified,unverified,unknown,filtered_unverified
